version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR.
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t telemetry1 .
      - docker tag telemetry1:latest ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/telemetry1:latest
      - echo Build was successful!      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/telemetry1:latest