version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR.
      - export ACC_ID=`curl http://169.254.169.254/latest/dynamic/instance-identity/document|grep accountId| awk '{print $3}'|sed  's/"//g'|sed 's/,//g'`
      - echo $ACC_ID
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin 553449525156.dkr.ecr.${AWS_REGION}.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t telemetry1 .
      - docker tag telemetry1:latest 553449525156.dkr.ecr.${AWS_REGION}.amazonaws.com/telemetry1:latest
      - echo Build was successful!      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 553449525156.dkr.ecr.${AWS_REGION}.amazonaws.com/telemetry1:latest