version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR.
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin ${ECRREPO}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t telemetry1 .
      - docker tag telemetry1:latest ${ECRREPO}:latest
      - echo Build was successful!      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push ${ECRREPO}:latest
      - printf '[{"name":"TelemetryApp","imageUri":"${ECRREPO}:latest"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json

  